# Generated by Django 6.0 on 2026-01-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='happy_clients',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
