# Generated by Django 6.0 on 2026-01-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_name_skill_skill_alter_skill_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='name',
        ),
    ]
