# Generated by Django 6.0 on 2026-01-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_skill_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_from',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
