# Generated by Django 6.0 on 2026-01-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_service_price_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fa-paint-brush', 'Creative / Design'), ('fa-pencil-alt', 'Editing / Writing'), ('fa-vector-square', 'Graphic Design'), ('fa-images', 'Photography / Visuals'), ('fa-laptop-code', 'Programming / Software'), ('fa-cogs', 'Engineering / Tech Solutions'), ('fa-server', 'IT / Hosting'), ('fa-lightbulb', 'Innovation / Ideas'), ('fa-briefcase', 'Business / Consultancy'), ('fa-chart-line', 'Analytics / Growth'), ('fa-handshake', 'Partnerships / Deals'), ('fa-users', 'Team Services / HR'), ('fa-star', 'Quality / Premium'), ('fa-check-circle', 'Reliability / Completion'), ('fa-gem', 'Luxury / Value'), ('fa-award', 'Recognition / Top Service')], max_length=50),
        ),
    ]
