# Generated by Django 6.0 on 2026-01-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
