# Generated by Django 6.0 on 2026-01-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_project_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
