# Generated by Django 6.0 on 2026-01-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Link to your Telegram channel/blog'),
        ),
    ]
